import type { Metadata } from "next"
import { Poppins, Chewy } from "next/font/google"
import "./globals.css"

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200","300", "400", "500", "600", "700"],
})

const chewy = Chewy({
  variable: "--font-chewy",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css"></link> */}
      </head>
      <body
        className={`
          ${poppins.variable}
          ${chewy.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  )
}
